apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      # could also specify path to extracted chart here
      # chart: ./helm-charts/bigbang/2.17.0/chart
      chart: ./helm-charts/bigbang/2.17.0/bigbang-2.17.0.tgz
      sourceRef:
        kind: GitRepository
        name: dkp-bigbang
        namespace: ${workspaceNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: bigbang-2.17.0-defaults
  targetNamespace: ${releaseNamespace}