apiVersion: v1
kind: ConfigMap
metadata:
  name: bigbang-2.17.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    # set ironbank registry credentials
    registryCredentials:
      registry: registry1.dso.mil
      username: username
      password: password

    # set containerd as container runtime in neuvector config
    neuvector:
      values:
        containerd:
          enabled: true

    # disable prometheus operator to not conflict with dkp's
    monitoring:
      values:
        prometheusOperator:
          enabled: false

    # disable kyverno policies, as some of the default installed Kyverno clusterpolicies can cause issues; alternatively, you could use policyexceptions
    kyvernoPolicies:
      enabled: false